version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:14
    container_name: climate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=climate_data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: climate_backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=climate_data
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # React/Vite frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: climate_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: 